# Generated by Django 5.0.6 on 2025-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_category_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
