# Generated by Django 5.0.6 on 2025-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_parkingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slot_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
