# Generated by Django 5.0.6 on 2025-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_category_slot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='current_slot',
            field=models.IntegerField(default=0),
        ),
    ]
